spring.application.name=Student-CURD

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/sstudent_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Avimal@2710}
spring.jpa.hibernate.ddl-auto= update
server.port=9000